project:
  type: book

book:
  title: "From User to Contributor: Organizing Events for First-Time Contributors"
  author: "Yanina Bellini Saibene and Steffi LaZerte"
  date: "10/10/2025"
  favicon: apple-touch-icon.png
  repo-url: https://github.com/ropenscilabs/FTCFOSS-Guide
  chapters:
    - index.qmd
    - pilot.qmd
    - event-overview.qmd
    - commcall.qmd
    - translathon.qmd
    - hackathon.qmd
  appendices:
    - resources.qmd
    - templates_emails.qmd
    - templates_forms.qmd
    - templates_social.qmd
    - examples_socials.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 3
    toc-expand: 3
  pdf:
    documentclass: scrreprt

